# **필수과제2**

# **2-1**

**전처리 X**

In [12]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('movie_rv.csv')

In [15]:
df=df.dropna()

In [16]:
df

Unnamed: 0        id  \
0                0   9976970   
1                1   3819312   
2                2  10265843   
3                3   9045019   
4                4   6483659   
...            ...       ...   
149995      149995   6222902   
149996      149996   8549745   
149997      149997   9311800   
149998      149998   2376369   
149999      149999   9619869   

                                                 document  label  
0                                     아 더빙.. 진짜 짜증나네요 목소리      0  
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1  
2                                       너무재밓었다그래서보는것을추천한다      0  
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0  
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1  
...                                                   ...    ...  
149995                                인간이 문제지.. 소는 뭔죄인가..      0  
149996                                      평점이 너무 낮아서...      1  
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0  
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1  
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0  

[149995 rows x 4 columns]

In [17]:
df_sp = df[:50000]

In [18]:
# Sklearn CounterVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
re_cv = CountVectorizer(max_features=1000)
df_sp_docu=df_sp['document']

In [20]:
re_cnv=re_cv.fit_transform(df_sp_docu)
re_cv.get_feature_names_out()[:100]

array(['0점', '0점은', '10', '10자', '10점', '1점', '1점도', '2점', '3류', '3점',
       '4점', '80년대', '90년대', '9점', 'b급', 'good', 'oo', 'ooo', 'ooo기',
       'ost', 'the', 'tv', 'ㄷㄷ', 'ㅅㅂ', 'ㅇㅇ', 'ㅉㅉ', 'ㅋㅋ', 'ㅋㅋㅋ', 'ㅋㅋㅋㅋ',
       'ㅋㅋㅋㅋㅋ', 'ㅎㅎ', 'ㅎㅎㅎ', 'ㅜㅜ', 'ㅠㅠ', 'ㅠㅠㅠ', 'ㅡㅡ', '가끔', '가는', '가볍게',
       '가서', '가슴', '가슴이', '가장', '가지고', '가진', '각본', '간만에', '갈수록', '감독',
       '감독님', '감독은', '감독의', '감독이', '감동', '감동과', '감동도', '감동을', '감동이',
       '감동적이고', '감동적인', '감사합니다', '갑자기', '강추', '같네요', '같다', '같습니다', '같아서',
       '같아요', '같은', '같은데', '같음', '같이', '개봉', '개뿔', '개연성', '개인적으로', '거의',
       '건지', '걸작', '겁나', '것도', '것은', '것을', '것이', '것이다', '게다가', '결국', '결말',
       '결말도', '결말은', '결말이', '계속', '공감이', '공포', '공포영화', '과연', '괜찮은', '괜히',
       '굉장히', '구성'], dtype=object)

In [21]:
!pip install konlpy
from konlpy.tag import Okt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 34.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 29.4 MB/s eta 0:00:00


In [22]:
tw_tag= Okt()
print(tw_tag.nouns(df_sp['document'][5]))

['막', '걸음', '마', '세', '초등학교', '학년', '생인', '영화', '반개', '움']


In [23]:
from sklearn.metrics.pairwise import cosine_similarity

st = len(df_sp_docu[4210])//2

source = df_sp_docu[4210][-st:]

In [24]:
df_sp_docu[4210]

'뻔했기에 좋았던 영화. 그리고 언제나 느끼는 거지만 다코타 패닝의 연기는 정말 최고.'

In [25]:
source_rv =re_cv.transform([source])

In [26]:
source_rv

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [27]:
sim_res=cosine_similarity(source_rv,re_cnv)

In [28]:
pd.DataFrame(sim_res)

0      1      2      3      4      5      6         7      8      9      \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  0.408248    0.0    0.0   

   ...  49990  49991  49992  49993  49994  49995  49996  49997  49998  49999  
0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[1 rows x 50000 columns]

In [29]:
len(sim_res[0])

50000

In [30]:
sim_res[0][4210]

0.6546536707079772

In [31]:
print(np.argmax(sim_res[0]))

5890


In [32]:
(-sim_res[0]).argsort()[:50]

array([ 5890, 24013, 44949, 46564, 39596,  6758, 38195, 34144, 23034,
        1589, 12675, 38364, 48346, 29239, 34648, 23568, 48268, 39206,
        2537, 35549, 22439,   213,  4210, 43186,  6091, 16708,  5038,
       31424, 12597, 10591, 40058, 22150, 39194, 14675,  3093, 33293,
       42138, 44267, 26177, 26834, 39254, 14071,  5361, 12771, 10567,
       23410, 33602, 44208, 33746, 41536])

In [68]:
df_sp['document'][5890]

'최고 예요 정말 감동했어요.'

In [67]:
df_sp['document'][44949]

'탄탄한시나리오와 오버랩되는 짜임잇는 연출, 완벽한 중년여배우의 연기... 최상의 조합이다. 다소지루할수잇엇지만 눈을 땔수없엇다. 그녀의 무조건적인 사랑에 가슴이 너무 아프다.. 이거보신분 컨빅션추천'

In [66]:
df_sp['document'][24013]

'정말 최고.... 정주행하게 만들다니...'

전처리를 하지 않았을 때, base 문장이 가장 높은 유사도를 띄는 것이 아닐 정도로 유사도 계산이 불안정함을 알 수 있음.


# **2-2**

**데이터셋 전처리**

In [33]:
def my_token(doc):
    return [token for token, pos in tw_tag.pos(doc) if pos in ['Noun','Verb']]

In [34]:
re_cv_mt = CountVectorizer(max_features=1000, tokenizer= my_token)

In [35]:
re_cnv_mt=re_cv_mt.fit_transform(df_sp_docu)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [36]:
re_cv_mt.get_feature_names_out()[:100]

array(['가', '가끔', '가는', '가면', '가서', '가슴', '가요', '가장', '가족', '가지', '가진',
       '가치', '각본', '간', '간다', '간만', '갈수록', '감', '감독', '감동', '감명', '감사합니다',
       '감상', '감성', '감정', '갑자기', '강', '강추', '개', '개그', '개봉', '개연', '개인',
       '개판', '거', '거기', '거리', '거의', '거지', '건', '건가', '건지', '걸', '걸까',
       '걸작', '겁나', '것', '게', '게이', '게임', '결론', '결말', '결혼', '경찰', '계속',
       '고', '고민', '고생', '곳', '공감', '공포', '공포영화', '과', '과거', '과연', '과정',
       '관', '관객', '관계', '관람', '관심', '광고', '괴물', '교훈', '구', '구성', '군대',
       '굳이', '굿', '귀신', '그', '그것', '그게', '그냥', '그녀', '그닥', '그대로', '그때',
       '그래픽', '그리', '그린', '그림', '극장', '극장판', '글', '급', '기', '기대', '기도',
       '기본'], dtype=object)

In [37]:
source_rv =re_cv_mt.transform([source])

In [38]:
sim_res2=cosine_similarity(source_rv,re_cnv_mt)

In [39]:
len(sim_res2[0])

50000

In [40]:
print(np.argmax(sim_res2[0]))

4210


In [41]:
sim_res2

array([[0.        , 0.18898224, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [44]:
pd.DataFrame(sim_res2)

0         1      2      3      4      5      6         7      8      9      \
0    0.0  0.188982    0.0    0.0   0.25    0.0    0.0  0.258199    0.0    0.0   

   ...  49990  49991  49992  49993  49994  49995     49996  49997  49998  \
0  ...    0.0    0.0    0.0    0.0    0.0    0.0  0.353553    0.0    0.0   

   49999  
0    0.0  

[1 rows x 50000 columns]

In [42]:
(-sim_res[0]).argsort()[:10]

array([ 5890, 24013, 44949, 46564, 39596,  6758, 38195, 34144, 23034,
        1589])

In [64]:
df_sp['document'][5890]

'최고 예요 정말 감동했어요.'

In [65]:
df_sp['document'][24013]

'정말 최고.... 정주행하게 만들다니...'

**불용어 제거**

In [2]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 20.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 23.7 MB/s eta 0:00:00


In [43]:
import pandas as pd
import re
from konlpy.tag import Okt

# 불용어 리스트
stopwords = [
    '은', '는', '이', '가', '을', '를', '에', '의', '로', '으로', '하다', '되다', '있다',
    '곳', '것', '거', '나', '저', '너', '그', '이것', '저것', '너무', '정말', '진짜', '아주', '매우',
    '그냥', '조금', '다소', '좀', '더', '또', '또한', '하지만', '그러나', '그래서', '왜', '어떻게',
    '이렇게', '저렇게', '많이', '좋다', '나쁘다', '크다', '작다', '많다', '적다', '같다',
    '다르다', '이미', '항상', '정도', '가장', '자주', '자꾸', '여전히', '계속', '아직', '다시',
    '처음', '마지막', '이번', '저번', '다음', '요즘', '때문', '비교적', '상당히', '훨씬', '얼마나',
    '거의', '특히', '결국', '실제로', '아니', '말', '이제', '대해', '관련', '사실', '사람', '대한'
]


# Okt 형태소 분석기 초기화
okt = Okt()

def preprocess_text(text):
    # 정규표현식을 사용해 한글과 공백을 제외하고 모두 제거
    text = re.sub(r'[^가-힣\s]', '', text)
    # 토큰화
    tokens = okt.morphs(text)
    # 불용어 제거
    tokens = [word for word in tokens if word not in stopwords]
    return ' '.join(tokens)

# 데이터 프레임의 텍스트에 전처리 적용
df_sp['docu_Okt'] = df_sp['document'].apply(preprocess_text)

<ipython-input-43-ecf56c566377>:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sp['docu_Okt'] = df_sp['document'].apply(preprocess_text)


In [45]:
pd.DataFrame(df_sp['docu_Okt'])

docu_Okt
0                                         아 더빙 짜증나네요 목소리
1                      흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍지 않구나
2                                무재 밓었 다그 래서 보는것을 추천 한 다
3                             교도소 이야기 구먼 솔직히 재미 없다 평점 조정
4      사이 몬페 익살스런 연기 돋보였던 영화 스파이더맨 에서 늙어 보이기만 했던 커스틴 ...
...                                                  ...
49996                                   보지마 셈 믿으세요 보지마 셈
49997                                              최고 졸작
49998                                      재밌고 좋았음 자 쓰라고
49999                                 소박하지만 잔잔한 감동 주는 영화
50000  재미 없으면 길게 만들지도 마 샬 리즈 테론 내 내 버럭 하고 틴 퀸 스튜어트 앞니...

[50000 rows x 1 columns]

In [46]:
re_cv_Okt = CountVectorizer(max_features=1000)
df_sp_docu_Okt=df_sp['docu_Okt']

re_cnv_Okt=re_cv_Okt.fit_transform(df_sp_docu_Okt)
re_cv_Okt.get_feature_names_out()[:100]

array(['가끔', '가는', '가면', '가서', '가슴', '가요', '가족', '가지', '가진', '가치', '각본',
       '간다', '간만', '갈수록', '감독', '감동', '감사합니다', '감상', '감성', '감정', '갑자기',
       '강추', '같네요', '같습니다', '같아', '같아서', '같아요', '같은', '같은데', '같음', '같이',
       '개그', '개봉', '개연', '개인', '개판', '거기', '거리', '거지', '건가', '건지', '걸작',
       '겁나', '게이', '게임', '결론', '결말', '결혼', '경찰', '고민', '고생', '공감', '공포',
       '공포영화', '과거', '과연', '과정', '관객', '관계', '관람', '관심', '광고', '괜찮은',
       '괜히', '괴물', '굉장히', '교훈', '구성', '군대', '굳이', '귀신', '귀여운', '귀엽고',
       '그것', '그게', '그나마', '그녀', '그닥', '그대로', '그때', '그래', '그래도', '그래픽',
       '그런', '그런데', '그런지', '그렇게', '그렇고', '그리', '그리고', '그린', '그림', '그만',
       '그저', '극장', '극장판', '근데', '기대', '기대하고', '기도'], dtype=object)

In [47]:
st = len(df_sp_docu_Okt[4210])//2

source = df_sp_docu_Okt[4210][-st:]

In [48]:
df_sp_docu_Okt[4210]

'뻔했기에 좋았던 영화 그리고 언제나 느끼는 거지 만 다코타 패닝 연기 최고'

In [49]:
source_rv =re_cv_Okt.transform([source])

In [50]:
sim_res3=cosine_similarity(source_rv,re_cnv_Okt)

In [51]:
len(sim_res3[0])

50000

In [52]:
print(np.argmax(sim_res3[0]))

2506


In [53]:
sim_res3

array([[0.        , 0.23570226, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [54]:
pd.DataFrame(sim_res3)

0         1      2      3         4      5      6         7      8      \
0    0.0  0.235702    0.0    0.0  0.235702    0.0    0.0  0.166667    0.0   

   9      ...  49990  49991  49992  49993  49994  49995     49996  49997  \
0    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0  0.408248    0.0   

   49998  49999  
0    0.0    0.0  

[1 rows x 50000 columns]

In [55]:
(-sim_res3[0]).argsort()[:50]

array([23457, 44949, 43018, 30685, 18565,  2506, 35838, 10964, 43192,
       45528, 25564, 10322, 47099, 37693, 33886, 45217, 43716, 45512,
       36353,  4210, 23193, 17360, 43709, 43607,  9651, 33605,  2404,
       25600, 30782, 34812,  2400, 16450, 38500, 35826, 46517, 47794,
       33054, 41154, 35750, 41135, 12364, 24013, 15461,  3804, 38642,
       23966, 15489, 38574, 29112,  8883])

In [56]:
sim_res3[0][23457]

0.816496580927726

In [57]:
sim_res3[0][4210]

0.6546536707079772

In [61]:
df_sp['document'][23457]

'연기 최고!'

In [60]:
df_sp['document'][44949]

'탄탄한시나리오와 오버랩되는 짜임잇는 연출, 완벽한 중년여배우의 연기... 최상의 조합이다. 다소지루할수잇엇지만 눈을 땔수없엇다. 그녀의 무조건적인 사랑에 가슴이 너무 아프다.. 이거보신분 컨빅션추천'

In [62]:
df_sp['document'][30685]

'무책임하고 이기적인 덜 떠러진 사랑을 보여준 남주인공 레너드 재수없고.. 미쉘년 부유한 가정환경에서 집안 망해서 자립심 없이 마약에도 손대고 가정 있는 남자 파탄 시키고 .. 결국 교훈은 사랑 사이에서 왔다갔다 하는 년놈과는 상종하지 말아야 함을..'

In [63]:
df_sp['document'][18565]

'최고의 연기'

전처리 이전 / 형태소 기반 전처리 / 정규표현식, 불용어 제거 전처리 총 3가지 데이터셋을 활용하여 코사인 유사도를 계산해보았다.

상위에 랭크된 몇개의 인덱스에 대하여 해당 리뷰를 찾아보았을 때 직관적으로 보기에는 3가지 데이터셋 모두 유사한 리뷰들을 추출해냈다고 볼 수 있다.

다만 전처리를 더 많이할수록 이전에는 유사도가 산정되지 않았던 리뷰데이터들도 유사도 값을 부여 받게 되었다는 점을 알 수 있다.